# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
